/**
 * dialed-core schema — the code form of docs/contracts.md. Not owned by any
 * lane; changes follow the schema-change protocol in CLAUDE.md. Better Auth
 * tables (users, sessions, accounts, verifications) are generated by its
 * adapter in 000 §5 and live in schema-auth.ts; app tables reference user
 * ids as plain text columns (FK constraints arrive with that migration).
 */
import {
  index,
  integer,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

export const userProfiles = sqliteTable("user_profiles", {
  userId: text("user_id").primaryKey(),
  displayName: text("display_name"),
  cityLabel: text("city_label"),
  lat: real("lat"),
  lng: real("lng"),
  thermalLevel: integer("thermal_level"),
  tempUnit: text("temp_unit", { enum: ["f", "c"] }),
  distanceUnit: text("distance_unit", { enum: ["mi", "km"] }),
  shareDefault: integer("share_default").notNull().default(1),
  onboardingComplete: integer("onboarding_complete").notNull().default(0),
});

export const brands = sqliteTable(
  "brands",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    normalized: text("normalized").notNull(),
    seeded: integer("seeded").notNull().default(0),
  },
  (t) => [uniqueIndex("brands_normalized").on(t.normalized)],
);

export const products = sqliteTable(
  "products",
  {
    id: text("id").primaryKey(),
    brandId: text("brand_id").notNull(),
    name: text("name").notNull(),
    normalizedName: text("normalized_name").notNull(),
    sourceUrl: text("source_url"),
    imageKey: text("image_key"),
    categoryHint: text("category_hint"),
    fabricComposition: text("fabric_composition"),
    fabricParts: text("fabric_parts"),
    weight: text("weight", { enum: ["light", "mid", "heavy"] }),
    fabric: text("fabric", {
      enum: ["synthetic", "merino", "cotton", "blend", "down"],
    }),
    windResistant: integer("wind_resistant"),
    waterResistant: integer("water_resistant"),
    extracted: text("extracted"),
    extractionStatus: text("extraction_status", {
      enum: ["none", "pending", "done", "failed"],
    })
      .notNull()
      .default("none"),
    status: text("status", { enum: ["active", "hidden"] })
      .notNull()
      .default("active"),
    createdBy: text("created_by").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [uniqueIndex("products_brand_name").on(t.brandId, t.normalizedName)],
);

export const productSnapshots = sqliteTable("product_snapshots", {
  id: text("id").primaryKey(),
  productId: text("product_id").notNull(),
  url: text("url").notNull(),
  r2Key: text("r2_key").notNull(),
  rung: text("rung", {
    enum: ["jsonld", "shopify", "og", "llm", "none"],
  }).notNull(),
  fetchedAt: integer("fetched_at").notNull(),
});

export const wardrobeItems = sqliteTable(
  "wardrobe_items",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    category: text("category", {
      enum: [
        "top",
        "bottom",
        "headwear",
        "neckwear",
        "gloves",
        "socks",
        "shoes",
        "accessory",
      ],
    }).notNull(),
    layer: text("layer", { enum: ["base", "mid", "outer"] }),
    weight: text("weight", { enum: ["light", "mid", "heavy"] }),
    fabric: text("fabric", {
      enum: ["synthetic", "merino", "cotton", "blend", "down"],
    }),
    windResistant: integer("wind_resistant"),
    waterResistant: integer("water_resistant"),
    estTempLowC: real("est_temp_low_c"),
    estTempHighC: real("est_temp_high_c"),
    brand: text("brand"),
    name: text("name").notNull(),
    size: text("size"),
    color: text("color"),
    photoKey: text("photo_key"),
    productUrl: text("product_url"),
    productId: text("product_id"),
    origin: text("origin", { enum: ["manual", "taplist"] })
      .notNull()
      .default("manual"),
    retired: integer("retired").notNull().default(0),
    visibility: text("visibility").notNull().default("ok"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    index("wardrobe_user_category").on(t.userId, t.category),
    index("wardrobe_product").on(t.productId),
  ],
);

export const runs = sqliteTable(
  "runs",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    source: text("source", { enum: ["manual", "file"] }).notNull(),
    startedAt: integer("started_at").notNull(),
    durationS: integer("duration_s").notNull(),
    distanceM: real("distance_m").notNull(),
    lat: real("lat"),
    lng: real("lng"),
    // mode:"boolean" so the storage detail stops at the data layer. SQLite
    // has no boolean and stores 0/1 either way, so the generated rebuild
    // changes no stored bytes — but the TypeScript type does become a real
    // boolean, which is the point. A future move to a provider with a
    // native boolean is then a column-type change and nothing else;
    // without it, every `!== 0` and `? 1 : 0` in the app has to move too.
    indoor: integer("indoor", { mode: "boolean" }).notNull().default(false),
    effort: text("effort", { enum: ["easy", "steady", "workout", "race"] }),
    title: text("title").notNull(),
    weatherStatus: text("weather_status", {
      enum: ["none", "pending", "attached", "manual", "failed"],
    })
      .notNull()
      .default("none"),
  },
  (t) => [index("runs_user_started").on(t.userId, t.startedAt)],
);

export const outfitEntries = sqliteTable(
  "outfit_entries",
  {
    id: text("id").primaryKey(),
    runId: text("run_id").notNull(),
    userId: text("user_id").notNull(),
    verdict: integer("verdict"),
    isPublic: integer("is_public").notNull().default(1),
    caption: text("caption"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    uniqueIndex("entries_run").on(t.runId),
    index("entries_user_created").on(t.userId, t.createdAt),
    index("entries_public_created").on(t.isPublic, t.createdAt),
  ],
);

export const outfitEntryItems = sqliteTable(
  "outfit_entry_items",
  {
    entryId: text("entry_id").notNull(),
    itemId: text("item_id").notNull(),
    flag: text("flag", { enum: ["too_much", "not_enough"] }),
    note: text("note"),
  },
  (t) => [uniqueIndex("entry_items_pk").on(t.entryId, t.itemId)],
);

export const entryTags = sqliteTable(
  "entry_tags",
  {
    entryId: text("entry_id").notNull(),
    tag: text("tag").notNull(),
  },
  (t) => [uniqueIndex("entry_tags_pk").on(t.entryId, t.tag)],
);

export const entryPhotos = sqliteTable("entry_photos", {
  id: text("id").primaryKey(),
  entryId: text("entry_id").notNull(),
  photoKey: text("photo_key").notNull(),
  position: integer("position").notNull(),
});

export const follows = sqliteTable(
  "follows",
  {
    followerId: text("follower_id").notNull(),
    followeeId: text("followee_id").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [uniqueIndex("follows_pk").on(t.followerId, t.followeeId)],
);

export const reactions = sqliteTable(
  "reactions",
  {
    entryId: text("entry_id").notNull(),
    userId: text("user_id").notNull(),
    kind: text("kind", { enum: ["useful"] })
      .notNull()
      .default("useful"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [uniqueIndex("reactions_pk").on(t.entryId, t.userId)],
);

export const notifications = sqliteTable(
  "notifications",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    kind: text("kind").notNull(),
    // Nullable: some kinds have no subject. `strava_broken` used to pass
    // the userId, which was "this kind has no subject" in disguise.
    // NOTE: SQLite treats NULLs as distinct in a UNIQUE index, so the
    // notifications_dedupe key does NOT dedupe subject-less kinds — those
    // must be guarded at the call site by only firing on a state
    // transition. See refreshStravaToken.
    subjectId: text("subject_id"),
    body: text("body").notNull(),
    read: integer("read", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    uniqueIndex("notifications_dedupe").on(t.userId, t.kind, t.subjectId),
    index("notifications_user_read").on(t.userId, t.read),
  ],
);

export const stravaConnections = sqliteTable("strava_connections", {
  userId: text("user_id").primaryKey(),
  athleteId: text("athlete_id").notNull(),
  accessToken: text("access_token").notNull(),
  refreshToken: text("refresh_token").notNull(),
  expiresAt: integer("expires_at").notNull(),
  status: text("status", { enum: ["ok", "broken"] })
    .notNull()
    .default("ok"),
  // Consecutive refresh failures, and when the current run of them began.
  // A single unconditional catch used to mark a connection `broken` on any
  // failure, so one network blip told the user to reconnect a working
  // account. Both columns are needed, not just the counter: how long three
  // failures take is entirely a function of how often something calls the
  // refresh, so the count alone cannot tell a 30-second outage from a real
  // revocation. Reset to 0/NULL on success.
  refreshFailureCount: integer("refresh_failure_count").notNull().default(0),
  refreshFirstFailedAt: integer("refresh_first_failed_at"),
});

export const processedWebhookEvents = sqliteTable(
  "processed_webhook_events",
  {
    objectId: text("object_id").notNull(),
    aspectType: text("aspect_type").notNull(),
    eventTime: integer("event_time").notNull(),
  },
  (t) => [
    uniqueIndex("webhook_events_pk").on(t.objectId, t.aspectType, t.eventTime),
  ],
);

export const cronCheckpoints = sqliteTable("cron_checkpoints", {
  cronName: text("cron_name").primaryKey(),
  lastRunAt: integer("last_run_at").notNull(),
});

export const imports = sqliteTable("imports", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  r2Key: text("r2_key").notNull(),
  status: text("status", {
    enum: ["pending", "processing", "done", "failed", "duplicate"],
  })
    .notNull()
    .default("pending"),
  failureReason: text("failure_reason"),
  runId: text("run_id"),
  createdAt: integer("created_at").notNull(),
});
