/**
 * dialed-core schema — the code form of docs/contracts.md. Not owned by any
 * lane; changes follow the schema-change protocol in CLAUDE.md. Better Auth
 * tables (users, sessions, accounts, verifications) are generated by its
 * adapter in 000 §5 and live in schema-auth.ts; app tables reference user
 * ids as plain text columns (FK constraints arrive with that migration).
 */
import { sql } from "drizzle-orm";

import { colorNames, garmentVisibilities } from "../lib/contracts";
import { EMAIL_PREFERENCE_KINDS } from "../lib/email";
import {
  index,
  integer,
  real,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

export const userProfiles = /*#__PURE__*/ sqliteTable(
  "user_profiles",
  {
    userId: text("user_id").primaryKey(),
    // The runner's handle (task 126, ACC-1; decision D-41 replaced
    // `display_name` with it). Stored lowercased, as the rule types it;
    // null until O0. `modules/account/username.ts` is the one writer.
    username: text("username"),
    cityLabel: text("city_label"),
    lat: real("lat"),
    lng: real("lng"),
    thermalLevel: integer("thermal_level"),
    tempUnit: text("temp_unit", { enum: ["f", "c"] }),
    distanceUnit: text("distance_unit", { enum: ["mi", "km"] }),
    shareDefault: integer("share_default", { mode: "boolean" })
      .notNull()
      .default(true),
    onboardingComplete: integer("onboarding_complete", { mode: "boolean" })
      .notNull()
      .default(false),
    // Task 106 ban mechanics. Nullable rather than a boolean + a date:
    // `bannedAt IS NOT NULL` is the ban, so there is one fact, not two
    // that can disagree. Sign-in, every public read and session revocation
    // all gate on the same column.
    bannedAt: integer("banned_at"),
    banReason: text("ban_reason"),
    // Set when a moderator force-renames the runner (task 128, round 27
    // #16): the reason from the fixed list, which O0's "USERNAME CHANGED BY
    // A MODERATOR" field quotes on their next load. Null means no re-pick
    // is owed; 126's screen clears it on Save or Keep.
    usernameResetReason: text("username_reset_reason"),
  },
  (t) => [
    // One index, two jobs. **Uniqueness regardless of case**: a handle is
    // stored lowercased, and NOCASE makes the index refuse "Maya" beside
    // "maya" even from a writer that forgot to lowercase. **Search's prefix
    // index**: people search is a prefix LIKE, which SQLite serves from an
    // index only when the index collation matches LIKE's, and LIKE is
    // case-insensitive for ASCII — so a BINARY index would scan the table
    // on every keystroke (rows scanned are what D1 bills).
    //
    // Verified with EXPLAIN QUERY PLAN on display_name, which this
    // replaces: "SEARCH user_profiles USING INDEX … (display_name>? AND
    // display_name<?)" with the NOCASE index, "SCAN" without.
    uniqueIndex("user_profiles_username_nocase").on(
      sql`${t.username} COLLATE NOCASE`,
    ),
  ],
);

/**
 * Every handle a runner has given up (task 126, ACC-1). Kept for two
 * reasons: `/@old` answers "This runner changed their name." rather than
 * a not-found or — worse — someone else's profile, and a handle a
 * moderator took away (ACC-12) is not free the moment it is taken.
 *
 * **Never reclaimable by another runner.** A retired handle stays here, so
 * the old link can never start pointing at a different person. Its own
 * runner may take it back, which deletes the row — unless it is locked.
 */
export const usernameHistory = /*#__PURE__*/ sqliteTable(
  "username_history",
  {
    username: text("username").primaryKey(),
    userId: text("user_id").notNull(),
    retiredAt: integer("retired_at").notNull(),
    // Set when a moderator took the handle away (task 128, round 27 #16):
    // a locked handle is refused to **everyone**, its former holder
    // included, so a force-rename cannot be undone from Settings. Null for
    // a handle the runner gave up themselves.
    lockedAt: integer("locked_at"),
  },
  (t) => [
    // Account deletion's read: every handle one runner held.
    index("username_history_user").on(t.userId),
  ],
);

/**
 * A runner's email switches (task 126, ACC-11; decision D-43; round 26
 * #19), one row per runner and kind they have touched. **No row means the
 * default**, which for the one kind today — the Strava run reminder — is
 * on. Transactional emails have no kind here and no switch: they are
 * always sent. There is no push column: PWA push is out of scope
 * (decision D-44).
 *
 * Read at send time by `modules/email`, and by task 127's reminder before
 * it owes one.
 */
export const notificationPreferences = /*#__PURE__*/ sqliteTable(
  "notification_preferences",
  {
    userId: text("user_id").notNull(),
    kind: text("kind", { enum: EMAIL_PREFERENCE_KINDS }).notNull(),
    email: integer("email", { mode: "boolean" }).notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => [uniqueIndex("notification_preferences_pk").on(t.userId, t.kind)],
);

/**
 * The live link for confirming an address (task 126, ACC-3 and ACC-8), one
 * per runner and purpose: `verify` confirms the address the account was
 * made with, `change` moves the account to a new one.
 *
 * **One row, so one live link.** Sending another replaces the hash, which
 * is what makes "the old one no longer works" true (round 26 #11) — Better
 * Auth's own verification tokens are signed and stateless, and cannot be
 * withdrawn. Only the SHA-256 of the token is kept, so a read of this
 * table cannot confirm an address. `used_at` is what tells "already
 * confirmed" (a used link) from "run out" (an expired or replaced one).
 */
export const emailVerifications = /*#__PURE__*/ sqliteTable(
  "email_verifications",
  {
    userId: text("user_id").notNull(),
    purpose: text("purpose", { enum: ["verify", "change"] }).notNull(),
    // The address the link confirms: the account's own for `verify`, the
    // new one for `change`. A `verify` link for an address the account
    // has since left confirms nothing.
    email: text("email").notNull(),
    tokenHash: text("token_hash").notNull(),
    expiresAt: integer("expires_at").notNull(),
    usedAt: integer("used_at"),
  },
  (t) => [uniqueIndex("email_verifications_pk").on(t.userId, t.purpose)],
);

/**
 * How many emails of one kind an address has been sent this hour (round
 * 26 #11: "That's 5 links this hour. You can send another at {time}.").
 *
 * **Keyed by the address, not the account**, and counted whether or not
 * the address has one: a limit that only an existing account could hit
 * would tell whoever hit it that the account exists — the thing Au4 is
 * drawn to never reveal. The key is `{kind}:{address}`.
 */
export const emailSendLimits = /*#__PURE__*/ sqliteTable("email_send_limits", {
  key: text("key").primaryKey(),
  windowStartedAt: integer("window_started_at").notNull(),
  sends: integer("sends").notNull(),
});

/**
 * How many times a signed-in runner has tried their current password this
 * window (ACC-8's email change). Better Auth's own limiter counts HTTP
 * requests; a server-side `auth.api.verifyPassword` call never passes
 * through it, so without this a session holder could guess the password
 * without limit. One row per runner, cleared by a right answer.
 */
export const passwordAttempts = /*#__PURE__*/ sqliteTable("password_attempts", {
  userId: text("user_id").primaryKey(),
  windowStartedAt: integer("window_started_at").notNull(),
  attempts: integer("attempts").notNull(),
});

/**
 * Invite codes (task 126, ACC-5; decision D-39; round 26 #20). `DIAL-XXXX`,
 * stored as `lib/access.ts` normalizes it, minted on Desk D7 — by hand,
 * or by answering an access request — or seeded for the owner as a
 * deployment step. A code works `max_uses` times; revoking one stops it at
 * once, and an undo clears `revoked_at` again.
 *
 * `idempotency_key` is D7's create form's (law 8b), scoped to the operator
 * who made it; `request_id` is the request a Send invite answered, unique
 * so a second press returns the code the first one minted.
 */
export const inviteCodes = /*#__PURE__*/ sqliteTable(
  "invite_codes",
  {
    id: text("id").primaryKey(),
    code: text("code").notNull(),
    label: text("label"),
    maxUses: integer("max_uses").notNull().default(1),
    createdBy: text("created_by"),
    idempotencyKey: text("idempotency_key"),
    requestId: text("request_id"),
    createdAt: integer("created_at").notNull(),
    revokedAt: integer("revoked_at"),
  },
  (t) => [
    uniqueIndex("invite_codes_code").on(t.code),
    uniqueIndex("invite_codes_idempotency").on(t.createdBy, t.idempotencyKey),
    uniqueIndex("invite_codes_request").on(t.requestId),
    // D7's Codes list, newest first.
    index("invite_codes_created").on(t.createdAt),
  ],
);

/**
 * A code spent on an account, one row per account (task 126, ACC-5).
 *
 * **Written before the account exists, by the account's own id.** Better
 * Auth makes the user row, so no batch of ours can hold it; its create
 * hook mints the id, and this row is the claim. `held_until` is what keeps
 * two sign-ups racing for a single-use code from both getting it: a row
 * counts against the code while its account exists *or* its hold is live,
 * so a sign-up that died between the claim and the account frees the
 * code when the hold runs out (`modules/account/invites.ts`).
 *
 * **A use is an address, and once made it is permanent.** Uses are
 * counted by distinct `email`, so a retried sign-up's second claim is the
 * same use, never a second one; and `confirmed_at` is set by the user
 * create hook's `after` once the account exists, so deleting that account
 * later does not hand the use back.
 */
export const inviteRedemptions = /*#__PURE__*/ sqliteTable(
  "invite_redemptions",
  {
    userId: text("user_id").primaryKey(),
    codeId: text("code_id").notNull(),
    email: text("email").notNull(),
    heldUntil: integer("held_until").notNull(),
    redeemedAt: integer("redeemed_at").notNull(),
    confirmedAt: integer("confirmed_at"),
  },
  (t) => [
    // A code's uses, counted at the claim and listed on D7.
    index("invite_redemptions_code").on(t.codeId),
    // A retried sign-up's live claim, found by address.
    index("invite_redemptions_email").on(t.email),
  ],
);

/**
 * Au5 · Request access (task 126, ACC-5; round 26 #20): one row per
 * address, lowercased. A repeat updates the note; the receipt is the same
 * whether the row is new, repeated, or the address already has an
 * account. D7 lists the pending ones oldest first.
 */
export const accessRequests = /*#__PURE__*/ sqliteTable(
  "access_requests",
  {
    id: text("id").primaryKey(),
    email: text("email").notNull(),
    note: text("note"),
    status: text("status", { enum: ["pending", "invited", "declined"] })
      .notNull()
      .default("pending"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => [
    uniqueIndex("access_requests_email").on(t.email),
    index("access_requests_status_created").on(t.status, t.createdAt),
  ],
);

export const brands = /*#__PURE__*/ sqliteTable(
  "brands",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    normalized: text("normalized").notNull(),
    seeded: integer("seeded", { mode: "boolean" }).notNull().default(false),
  },
  (t) => [uniqueIndex("brands_normalized").on(t.normalized)],
);

export const products = /*#__PURE__*/ sqliteTable(
  "products",
  {
    id: text("id").primaryKey(),
    brandId: text("brand_id").notNull(),
    name: text("name").notNull(),
    normalizedName: text("normalized_name").notNull(),
    sourceUrl: text("source_url"),
    imageKey: text("image_key"),
    categoryHint: text("category_hint"),
    // The specific thing this product *is* — singlet, tee, half-zip.
    //
    // Design's Z screen: "type is a property of the product, not of the
    // garment". It is written by enrichment reading a product page, never
    // by a user, and never parsed out of free text — a garment named
    // "Crew for cold L/S days" would be filed wrong, silently, forever.
    //
    // Distinct from `category_hint`, which holds a *category* enum value
    // used to pre-fill F's one-tap category. Design's note calls the
    // garment column "a cache of products.category_hint"; that is the
    // right relationship against the wrong column name, since the two
    // hold different vocabularies.
    type: text("type"),
    fabricComposition: text("fabric_composition"),
    fabricParts: text("fabric_parts"),
    weight: text("weight", { enum: ["light", "mid", "heavy"] }),
    fabric: text("fabric", {
      enum: ["synthetic", "merino", "cotton", "blend", "down"],
    }),
    // mode:"boolean" so the storage detail stops at the data layer. SQLite
    // has no boolean and stores 0/1 either way, so the rebuild the codec
    // triggers changes no stored bytes — what changes is that a component
    // asking "is this retired?" gets a boolean instead of comparing to 1.
    // Nullable here: null means "not stated", which is distinct from false
    // and is what lets a product default fill the gap.
    windResistant: integer("wind_resistant", { mode: "boolean" }),
    waterResistant: integer("water_resistant", { mode: "boolean" }),
    extracted: text("extracted"),
    extractionStatus: text("extraction_status", {
      enum: ["none", "pending", "done", "failed"],
    })
      .notNull()
      .default("none"),
    status: text("status", { enum: ["active", "hidden"] })
      .notNull()
      .default("active"),
    createdBy: text("created_by").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [uniqueIndex("products_brand_name").on(t.brandId, t.normalizedName)],
);

export const productSnapshots = /*#__PURE__*/ sqliteTable("product_snapshots", {
  id: text("id").primaryKey(),
  productId: text("product_id").notNull(),
  url: text("url").notNull(),
  r2Key: text("r2_key").notNull(),
  // "text" is the page's rendered text, searched for a fibre percentage —
  // added by 107 once measurement showed composition is almost never in a
  // declared field. Type-level only: the column is plain TEXT with no CHECK,
  // so widening the set needs no migration.
  rung: text("rung", {
    enum: ["jsonld", "shopify", "og", "text", "llm", "none"],
  }).notNull(),
  fetchedAt: integer("fetched_at").notNull(),
});

export const wardrobeItems = /*#__PURE__*/ sqliteTable(
  "wardrobe_items",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    category: text("category", {
      enum: [
        "top",
        "bottom",
        "headwear",
        "neckwear",
        "gloves",
        "socks",
        "shoes",
        "accessory",
      ],
    }).notNull(),
    // A **cache of the product's type**, not a fact about this garment.
    //
    // Design's Z screen settles where it comes from: written on match and
    // on enrichment, never by a user, never parsed from a name. F does not
    // ask for it — "a second one-tap row is cheap to build and expensive
    // every single time", and charging a tap for a filter facet inverts
    // F's argument that identity is the only thing worth one.
    //
    // So a garment with no product has no type, and that is a state the UI
    // renders rather than hides: the detail subtitle is
    // `type ?? categoryLabel + " · GENERIC"`, and type filter chips are
    // built from the types actually present in a category, so an all-generic
    // category shows no chips at all — correct, not broken.
    //
    // Nullable for a reason that outlives launch: **a garment often does
    // not know its own type, and should not have to.** The tap-list knows
    // (the row *is* the type). A manual add does not — screen F collects
    // brand, model and a one-tap category, and no type field, deliberately:
    // the design shows the type on the garment *detail* ("Tracksmith
    // Harrier / LONG SLEEVE HALF-ZIP") rather than asking for it. It is
    // there to be inferred, most obviously from the product name, which is
    // what enrichment already does for `products.category_hint`.
    //
    // NOT NULL would force screen F to grow a required picker between the
    // user and saving a shirt, to make the system's inference the user's
    // chore. If that turns out to be wanted it is a product decision and a
    // later tightening, which expand->contract supports.
    //
    // (The usual "existing rows have none" argument does not apply — there
    // is no production data yet. This column would be nullable anyway.)
    //
    // Deliberately NOT enum-constrained here, unlike `category`. The legal
    // values depend on the category, which a column check cannot express;
    // `garmentSchema` in lib/contracts.ts is the gate, and every write goes
    // through it. A widened column with a narrow parser beats a column that
    // has to list all 19 values and cannot say which go with which.
    type: text("type"),
    layer: text("layer", { enum: ["base", "mid", "outer"] }),
    weight: text("weight", { enum: ["light", "mid", "heavy"] }),
    fabric: text("fabric", {
      enum: ["synthetic", "merino", "cotton", "blend", "down"],
    }),
    // mode:"boolean" so the storage detail stops at the data layer. SQLite
    // has no boolean and stores 0/1 either way, so the rebuild the codec
    // triggers changes no stored bytes — what changes is that a component
    // asking "is this retired?" gets a boolean instead of comparing to 1.
    // Nullable here: null means "not stated", which is distinct from false
    // and is what lets a product default fill the gap.
    windResistant: integer("wind_resistant", { mode: "boolean" }),
    waterResistant: integer("water_resistant", { mode: "boolean" }),
    estTempLowC: real("est_temp_low_c"),
    estTempHighC: real("est_temp_high_c"),
    brand: text("brand"),
    name: text("name").notNull(),
    size: text("size"),
    // The colourway the runner typed — "Obsidian". Stays exactly what it
    // was: design round 11 §AH keeps it as the row's caption beside the
    // structured name below, untouched and never parsed into one.
    color: text("color"),
    // §AH's thirteen locked names, two classes (lib/contracts.ts derives
    // the enum from the classes). Nullable and never backfilled — mapping
    // "Obsidian" to black is the parser round 5 refused.
    colorName: text("color_name", { enum: colorNames }),
    // §AH level 2. Six-digit lowercase hex with the '#'. Optional beside
    // an optional name: a runner who gives one gets a coarser Call, not a
    // different one. Enrichment may propose the *name*; it never proposes
    // a hex.
    colorHex: text("color_hex"),
    // **Not `visibility`.** That column is four lines down and means the
    // moderation state; this is §AH's garment property — how much a piece
    // is built to be seen. One word, two facts, one table: the collision
    // is real and naming this one `visibility` would have overwritten a
    // trust-and-safety field with nothing failing loudly.
    //
    // All three values matter. `hi_viz` exempts a garment from the colour
    // tiebreak entirely (§AH rule 04, "safety because the runner said so,
    // never because a hex is bright"); `reflective` does not, because the
    // base colour is still what shows.
    visibilityLevel: text("visibility_level", { enum: garmentVisibilities }),
    photoKey: text("photo_key"),
    productUrl: text("product_url"),
    productId: text("product_id"),
    origin: text("origin", { enum: ["manual", "taplist"] })
      .notNull()
      .default("manual"),
    // Client-generated, minted when the form mounts and resent on every
    // retry of that same submission (law 8b). Nullable: rows created by
    // anything other than a form have no key and must not be forced to
    // invent one.
    idempotencyKey: text("idempotency_key"),
    retired: integer("retired", { mode: "boolean" }).notNull().default(false),
    // When the piece was retired, in epoch seconds — round 22's
    // `[RETIRED SEP 12]`. Written in the same statement as `retired` and
    // cleared with it on unretire. Nullable and never backfilled: a piece
    // retired before this column existed shows `[RETIRED]` undated rather
    // than a date nobody recorded.
    retiredAt: integer("retired_at"),
    // Reserved by 000 as untyped text written by nobody; task 106 is what
    // it was reserved for. Typing it is type-level only in drizzle — the
    // emitted SQL for a text enum carries no CHECK — so this narrows the
    // compiler without a table rebuild. Same vocabulary as
    // entry_photos.screen_status on purpose: a garment photo and an entry
    // photo are screened by the same path and must not drift into two
    // spellings of one state. 'ok' is the pre-106 default and means
    // "never screened", which is distinct from 'pass'.
    visibility: text("visibility", {
      enum: ["ok", "pending", "pass", "flagged", "hidden_pending_review"],
    })
      .notNull()
      .default("ok"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    index("wardrobe_user_category").on(t.userId, t.category),
    index("wardrobe_product").on(t.productId),
    // Scoped to the user, like runs': keys come from the client, so one
    // account's key must never return another's row.
    uniqueIndex("wardrobe_idempotency").on(t.userId, t.idempotencyKey),
  ],
);

export const runs = /*#__PURE__*/ sqliteTable(
  "runs",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    source: text("source", { enum: ["manual", "file"] }).notNull(),
    startedAt: integer("started_at").notNull(),
    durationS: integer("duration_s").notNull(),
    distanceM: real("distance_m").notNull(),
    lat: real("lat"),
    lng: real("lng"),
    // mode:"boolean" so the storage detail stops at the data layer. SQLite
    // has no boolean and stores 0/1 either way, so the generated rebuild
    // changes no stored bytes — but the TypeScript type does become a real
    // boolean, which is the point. A future move to a provider with a
    // native boolean is then a column-type change and nothing else;
    // without it, every `!== 0` and `? 1 : 0` in the app has to move too.
    indoor: integer("indoor", { mode: "boolean" }).notNull().default(false),
    effort: text("effort", { enum: ["easy", "steady", "workout", "race"] }),
    title: text("title").notNull(),
    // Client-generated, one per composed submission. A double-click, a
    // browser POST replay or a retry on a flaky connection all resend the
    // same key, and the UNIQUE index below turns the second insert into a
    // no-op instead of a second run. Nullable because imported runs have
    // no form behind them.
    idempotencyKey: text("idempotency_key"),
    weatherStatus: text("weather_status", {
      enum: ["none", "pending", "attached", "manual", "failed"],
    })
      .notNull()
      .default("none"),
    // When the Strava reminder this file run answers landed (task 127,
    // round 25: "one upload clears one reminder"). Set when an import
    // clears a reminder, or when a reminder arrives for a file already
    // uploaded; a run with it set can neither clear nor suppress another.
    // NULL for a manual run and for a file with no reminder yet.
    reminderMatchedAt: integer("reminder_matched_at"),
  },
  (t) => [
    index("runs_user_started").on(t.userId, t.startedAt),
    // Scoped to the user: keys are client-generated, so one user's key must
    // never collide with another's.
    uniqueIndex("runs_idempotency").on(t.userId, t.idempotencyKey),
  ],
);

export const outfitEntries = /*#__PURE__*/ sqliteTable(
  "outfit_entries",
  {
    id: text("id").primaryKey(),
    runId: text("run_id").notNull(),
    userId: text("user_id").notNull(),
    verdict: integer("verdict"),
    isPublic: integer("is_public", { mode: "boolean" }).notNull().default(true),
    // Task 106. Deliberately NOT `isPublic`: that column is the runner's own
    // sharing choice, and a moderator writing to it would silently rewrite a
    // preference the runner set. Two different facts, two columns — an entry
    // hidden for review that the owner had shared must go back to shared when
    // it is approved, which is only knowable if nothing overwrote it.
    //
    // 'ok' is the default and the overwhelmingly common value. Public reads
    // require it; the owner's own reads ignore it, so a reported entry stays
    // visible to its author with an "under review" badge.
    moderationStatus: text("moderation_status", {
      enum: ["ok", "hidden_pending_review", "removed"],
    })
      .notNull()
      .default("ok"),
    caption: text("caption"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    uniqueIndex("entries_run").on(t.runId),
    index("entries_user_created").on(t.userId, t.createdAt),
    // moderationStatus joins the covering index because every public read
    // now filters on it too. Left out, the feed query filters in memory
    // after LIMIT — which CLAUDE.md's D1 discipline calls out by name as
    // returning "the survivors of the first 200 rows".
    index("entries_public_created").on(
      t.isPublic,
      t.moderationStatus,
      t.createdAt,
    ),
    // One runner's public entries, newest first: the Following feed's
    // per-author seek (FEED-5 review, `feed/feed.ts`). Driving the page
    // from the viewer's followees, each read to at most a page, is what
    // makes the rows it scans scale with who they follow rather than with
    // every runner on the site.
    index("entries_user_public_created").on(
      t.userId,
      t.isPublic,
      t.moderationStatus,
      t.createdAt,
    ),
  ],
);

export const outfitEntryItems = /*#__PURE__*/ sqliteTable(
  "outfit_entry_items",
  {
    entryId: text("entry_id").notNull(),
    itemId: text("item_id").notNull(),
    flag: text("flag", { enum: ["too_much", "not_enough"] }),
    note: text("note"),
  },
  (t) => [uniqueIndex("entry_items_pk").on(t.entryId, t.itemId)],
);

export const entryTags = /*#__PURE__*/ sqliteTable(
  "entry_tags",
  {
    entryId: text("entry_id").notNull(),
    tag: text("tag").notNull(),
  },
  (t) => [uniqueIndex("entry_tags_pk").on(t.entryId, t.tag)],
);

export const entryPhotos = /*#__PURE__*/ sqliteTable(
  "entry_photos",
  {
    id: text("id").primaryKey(),
    entryId: text("entry_id").notNull(),
    photoKey: text("photo_key").notNull(),
    position: integer("position").notNull(),
    // Client-generated, minted when the form mounts and resent on every
    // retry of that same submission (law 8b). Nullable: rows created by
    // anything other than a form have no key and must not be forced to
    // invent one.
    idempotencyKey: text("idempotency_key"),
    // Task 106 photo screening. 'pending' is the durable marker the
    // screening-retry cron reconciles against (law 8c) — the reason this
    // path needs no queue. The owner's own reads ignore this column; every
    // public read requires 'pass'. So a classifier outage degrades to
    // "nobody else sees it yet" and never to a wrong answer or a failed
    // save (law 5).
    screenStatus: text("screen_status", {
      enum: ["pending", "pass", "flagged", "hidden_pending_review"],
    })
      .notNull()
      .default("pending"),
  },
  (t) => [
    // The retry sweep reads "still pending, oldest first".
    index("entry_photos_screen_status").on(t.screenStatus, t.id),
    // Scoped to the *entry*, not the user, which is narrower and needs no
    // denormalised owner column: an entry has exactly one owner, and the
    // upload path already refuses a caller who does not own it, so two
    // users cannot reach the same key. Every other key in this schema is
    // user-scoped because its table has no such parent.
    uniqueIndex("entry_photos_idempotency").on(t.entryId, t.idempotencyKey),
  ],
);

export const follows = /*#__PURE__*/ sqliteTable(
  "follows",
  {
    followerId: text("follower_id").notNull(),
    followeeId: text("followee_id").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [uniqueIndex("follows_pk").on(t.followerId, t.followeeId)],
);

export const reactions = /*#__PURE__*/ sqliteTable(
  "reactions",
  {
    entryId: text("entry_id").notNull(),
    userId: text("user_id").notNull(),
    kind: text("kind", { enum: ["useful"] })
      .notNull()
      .default("useful"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [uniqueIndex("reactions_pk").on(t.entryId, t.userId)],
);

export const notifications = /*#__PURE__*/ sqliteTable(
  "notifications",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    kind: text("kind").notNull(),
    // Nullable: a kind may have no subject.
    // NOTE: SQLite treats NULLs as distinct in a UNIQUE index, so the
    // notifications_dedupe key does NOT dedupe subject-less kinds — those
    // must be guarded at the call site.
    subjectId: text("subject_id"),
    body: text("body").notNull(),
    read: integer("read", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    uniqueIndex("notifications_dedupe").on(t.userId, t.kind, t.subjectId),
    index("notifications_user_read").on(t.userId, t.read),
    // The daily Strava prune's read (task 127, STR-10): reminders of one
    // kind older than a cutoff. Without it the prune scans the table.
    index("notifications_kind_created").on(t.kind, t.createdAt),
  ],
);

export const stravaConnections = /*#__PURE__*/ sqliteTable(
  "strava_connections",
  {
    userId: text("user_id").primaryKey(),
    athleteId: text("athlete_id").notNull(),
    // The only token kept (D-54), and only to revoke the grant: on
    // disconnect, account deletion and deauthorization. `/oauth/revoke`
    // takes it, and it does not expire until rotated. The access token and
    // its expiry are never stored — nothing here reads activity data.
    refreshToken: text("refresh_token").notNull(),
    // When this grant was made, epoch seconds (task 127). A deauthorization
    // event older than this is about an earlier grant, and must not delete
    // a runner's newer connection. NULL on rows made before the column.
    connectedAt: integer("connected_at"),
  },
  (t) => [
    // One Strava athlete maps to at most one user. Without this, two
    // accounts could connect the same athlete and the webhook's
    // athlete -> user lookup would pick between them arbitrarily, sending
    // someone else's run reminder to the wrong person. Found by a
    // consumer test that reused an athlete id.
    uniqueIndex("strava_connections_athlete").on(t.athleteId),
  ],
);

/**
 * Transactional outbox for Strava grant revocations.
 *
 * Disconnecting is two writes to two systems — delete the local row, tell
 * Strava — and no transaction spans both. Doing them in sequence means a
 * queue failure after the delete leaves a live grant with no record that it
 * exists: silent, unrecoverable, and invisible to us and the user alike.
 *
 * So the *intent* is written to the database in the same batch as the
 * delete, which is atomic, and dispatch becomes a separate at-least-once
 * concern. The row is deleted once Strava confirms. A row still here is a
 * revocation that has not happened yet, which the digest can see and
 * re-dispatch.
 */
export const stravaRevocations = /*#__PURE__*/ sqliteTable(
  "strava_revocations",
  {
    id: text("id").primaryKey(),
    createdAt: integer("created_at").notNull(),
    // What the drain revokes with (task 127, STR-2), copied from the
    // connection row, which is already gone by the time this exists. A
    // refresh token does not expire until it is rotated — which nothing
    // does once the connection row is gone.
    refreshToken: text("refresh_token").notNull(),
  },
);

/**
 * The generic transactional outbox (law 8c): work owed to another system,
 * written in the same `db.batch()` as the D1 change that created the debt.
 *
 * `kind` + `payload` are a wire format between deploys (law 9), parsed on
 * the way out by `outboxMessageSchema` in lib/outbox.ts. The UNIQUE pair is
 * what makes a second enqueue of the same debt one row rather than two.
 * A row here is work not yet confirmed done: a fast path deletes it on
 * success, and the daily drainer in modules/ops re-drives what is left,
 * backing off by `next_attempt_at` and counting `attempts`.
 *
 * `strava_revocations` above predates this and is deliberately not folded
 * in yet (docs/deferred.md).
 */
export const outbox = /*#__PURE__*/ sqliteTable(
  "outbox",
  {
    id: text("id").primaryKey(),
    kind: text("kind").notNull(),
    dedupeKey: text("dedupe_key").notNull(),
    payload: text("payload").notNull(),
    attempts: integer("attempts").notNull().default(0),
    nextAttemptAt: integer("next_attempt_at").notNull(),
    createdAt: integer("created_at").notNull(),
    // Task 126 (PR #119 review): when an email row's send landed, and the
    // id the sender gave it. Written in one statement right after the
    // send, before the delete — a row that has it was sent, and the drain
    // deletes it rather than sending again.
    sentAt: integer("sent_at"),
    messageId: text("message_id"),
  },
  (t) => [
    uniqueIndex("outbox_kind_dedupe").on(t.kind, t.dedupeKey),
    // The drainer's read: due rows of one kind, oldest first.
    index("outbox_kind_due").on(t.kind, t.nextAttemptAt),
  ],
);

export const processedWebhookEvents = /*#__PURE__*/ sqliteTable(
  "processed_webhook_events",
  {
    objectId: text("object_id").notNull(),
    aspectType: text("aspect_type").notNull(),
    eventTime: integer("event_time").notNull(),
  },
  (t) => [
    uniqueIndex("webhook_events_pk").on(t.objectId, t.aspectType, t.eventTime),
    // The same prune deletes keys older than a week by event time.
    index("webhook_events_time").on(t.eventTime),
  ],
);

export const cronCheckpoints = /*#__PURE__*/ sqliteTable("cron_checkpoints", {
  cronName: text("cron_name").primaryKey(),
  lastRunAt: integer("last_run_at").notNull(),
});

export const imports = /*#__PURE__*/ sqliteTable(
  "imports",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    r2Key: text("r2_key").notNull(),
    status: text("status", {
      enum: ["pending", "processing", "done", "failed", "duplicate"],
    })
      .notNull()
      .default("pending"),
    failureReason: text("failure_reason"),
    runId: text("run_id"),
    createdAt: integer("created_at").notNull(),
    // Client-generated, minted when the form mounts and resent on every
    // retry of that same submission (law 8b). Nullable: rows created by
    // anything other than a form have no key and must not be forced to
    // invent one.
    idempotencyKey: text("idempotency_key"),
  },
  (t) => [uniqueIndex("imports_idempotency").on(t.userId, t.idempotencyKey)],
);

/**
 * Task 106's trust & safety tables. All additive (CLAUDE.md schema protocol):
 * new tables, plus nullable columns on existing ones, so this is expand-only
 * and safe to deploy ahead of the code that reads it (law 8).
 */

/**
 * A report filed by one user against one thing. `subjectType` discriminates
 * what `subjectId` points at — an entry, a photo, a profile, or a product
 * name (D-26 makes product names UGC and therefore reportable).
 *
 * The UNIQUE index is the whole auto-hide mechanism: the packet's threshold
 * is "N reports from *distinct* users", and the only way to make that true
 * under retries and double-clicks (law 8b) is to refuse a user's second
 * report of the same subject at the storage layer. Counting rows is then
 * counting people, which is what the rule actually means.
 */
export const reports = /*#__PURE__*/ sqliteTable(
  "reports",
  {
    id: text("id").primaryKey(),
    reporterId: text("reporter_id").notNull(),
    subjectType: text("subject_type", {
      enum: ["entry", "photo", "profile", "product"],
    }).notNull(),
    subjectId: text("subject_id").notNull(),
    reason: text("reason", {
      enum: ["explicit", "harassment", "spam", "not_theirs", "other"],
    }).notNull(),
    note: text("note"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    // One report per person per subject. Not a dedupe convenience: it is
    // what makes a COUNT(*) over this table a count of distinct reporters.
    uniqueIndex("reports_one_per_reporter").on(
      t.reporterId,
      t.subjectType,
      t.subjectId,
    ),
    // The auto-hide count, and the reviewer's "what else was said about
    // this" read. Both filter on the subject, so the subject leads.
    index("reports_subject").on(t.subjectType, t.subjectId),
  ],
);

/**
 * One row per thing awaiting a human, not one per report — three reports
 * about the same entry are one decision. `status` is the claim column
 * (law 2): the review UI claims a row before acting on it, so two open
 * tabs cannot both resolve it.
 */
export const reviewQueue = /*#__PURE__*/ sqliteTable(
  "review_queue",
  {
    id: text("id").primaryKey(),
    subjectType: text("subject_type", {
      enum: ["entry", "photo", "profile", "product"],
    }).notNull(),
    subjectId: text("subject_id").notNull(),
    // Why it is here: reports crossed the threshold, or the classifier
    // flagged it. The reviewer reads a photo flagged by a model
    // differently from one three people objected to.
    source: text("source", { enum: ["reports", "classifier"] }).notNull(),
    status: text("status", {
      enum: ["pending", "reviewing", "approved", "removed"],
    })
      .notNull()
      .default("pending"),
    resolvedBy: text("resolved_by"),
    resolvedAt: integer("resolved_at"),
    // When a reviewer claimed it, and the only thing that can ever release
    // the claim. `status='reviewing'` is a lock held by a browser tab, and
    // a tab that is closed, crashed or simply walked away from used to
    // hold it forever: the row left the queue, no one was looking at it,
    // and nothing anywhere said so. Null unless claimed. Raised on PR #73.
    claimedAt: integer("claimed_at"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    // One open decision per subject; a second trigger updates rather than
    // stacking a duplicate in front of the reviewer.
    uniqueIndex("review_queue_subject").on(t.subjectType, t.subjectId),
    // The stale-claim sweep's only query: rows still `reviewing`, oldest
    // claim first.
    index("review_queue_claimed").on(t.status, t.claimedAt),
    // The queue page and the digest's depth count both read
    // "pending, oldest first" — a covering index for the only query.
    index("review_queue_status_created").on(t.status, t.createdAt),
  ],
);

/**
 * Domains product URLs may not point at. Seeded empty; the review flow adds
 * to it. Stored as the bare registrable host, lowercased, which is what the
 * save path compares against — never the full URL.
 */
export const domainDenylist = /*#__PURE__*/ sqliteTable("domain_denylist", {
  domain: text("domain").primaryKey(),
  addedBy: text("added_by").notNull(),
  reason: text("reason"),
  createdAt: integer("created_at").notNull(),
});

/**
 * What the classifier said about one photo, kept separately from the
 * photo's `screen_status` so a threshold can be re-tuned against real
 * scores after launch without re-classifying anything.
 *
 * `scores` is the raw per-category JSON as returned. Parsed through a zod
 * codec on read like any other stored blob — it is our own write, but the
 * shape came from outside and the rule does not care which.
 */
export const photoScreenings = /*#__PURE__*/ sqliteTable(
  "photo_screenings",
  {
    id: text("id").primaryKey(),
    // 'entry' | 'garment' — the two photo kinds, in their own tables.
    photoScope: text("photo_scope", { enum: ["entry", "garment"] }).notNull(),
    photoId: text("photo_id").notNull(),
    model: text("model").notNull(),
    scores: text("scores").notNull(),
    // Three bands, not two (PR #73). `review` is the middle one: the photo
    // stays visible and a person is asked to look anyway, so a borderline
    // score buys calibration instead of costing a runner their photo.
    // Widening a drizzle text enum is a TypeScript change only — the column
    // is plain `text` with no CHECK, so there is no migration in it.
    decision: text("decision", {
      enum: ["pass", "review", "flag"],
    }).notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [index("photo_screenings_photo").on(t.photoScope, t.photoId)],
);

/**
 * A block: `blockerId` no longer sees `blockedId`, and vice versa (W2's
 * copy promises both directions). Distinct from a ban, which is ours;
 * a block is the runner's own and is never announced.
 *
 * Deliberately NOT read by the conditions aggregate — W2 states that a
 * blocked runner's verdicts still count in the anonymous numbers, because
 * those name nobody. `test/.../blocks.test.ts` pins that.
 */
export const blocks = /*#__PURE__*/ sqliteTable(
  "blocks",
  {
    blockerId: text("blocker_id").notNull(),
    blockedId: text("blocked_id").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    uniqueIndex("blocks_pk").on(t.blockerId, t.blockedId),
    // The reverse direction is a query too: "who has blocked me" filters
    // my content out of their feed, and without this it is a table scan.
    index("blocks_blocked").on(t.blockedId),
  ],
);

/**
 * What a person at the Desk did to someone's content, and why (task 128 ·
 * SAF-5, SAF-6, SAF-4): the audit a DMCA takedown needs ("who, what and
 * why"), the record the EU DSA's statement of reasons is written from, and
 * the only place a quarantine's preserved object is named.
 *
 * Append-only. A subject can be acted on more than once (banned, unbanned,
 * banned again), so nothing here is unique but the id. `subjectOwnerId`
 * is the runner the action was taken against, kept so their notice and any
 * later appeal can find it after the subject itself is gone.
 */
export const moderationActions = /*#__PURE__*/ sqliteTable(
  "moderation_actions",
  {
    id: text("id").primaryKey(),
    actorId: text("actor_id").notNull(),
    action: text("action", {
      enum: ["remove", "quarantine", "takedown", "ban", "unban", "rename"],
    }).notNull(),
    subjectType: text("subject_type", {
      enum: ["entry", "photo", "profile"],
    }).notNull(),
    subjectId: text("subject_id").notNull(),
    subjectOwnerId: text("subject_owner_id"),
    // The operator's words, word for word — what the runner is told.
    reason: text("reason").notNull(),
    // Where a quarantined object was moved to; null for everything else.
    preservedKey: text("preserved_key"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    index("moderation_actions_subject").on(t.subjectType, t.subjectId),
    index("moderation_actions_owner").on(t.subjectOwnerId, t.createdAt),
  ],
);

/**
 * Suspected CSAM, held for the owner's report to NCMEC (task 128 · SAF-5;
 * decision D-70). A quarantine deletes the entry or photo from every table
 * a read touches — which is what hides it at once, from everyone, with no
 * filter to forget — and moves what it was here first: the rows as they
 * stood, the uploader, and where the bytes were copied to.
 *
 * **Locked and admin-only.** Nothing updates or deletes a row, no runner-
 * facing read joins this table, and its one read (`quarantinedContent` in
 * `modules/safety`) refuses anyone but an admin. `retainUntil` is a year
 * after the quarantine; nothing purges on it yet (deployment plan §8).
 * No foreign keys, on purpose: deleting the account must not take the
 * evidence with it.
 */
export const quarantinedContent = /*#__PURE__*/ sqliteTable(
  "quarantined_content",
  {
    id: text("id").primaryKey(),
    // The audit row that records who quarantined it and why.
    moderationActionId: text("moderation_action_id").notNull(),
    subjectType: text("subject_type", { enum: ["entry", "photo"] }).notNull(),
    subjectId: text("subject_id").notNull(),
    uploaderId: text("uploader_id").notNull(),
    entryId: text("entry_id").notNull(),
    // JSON: the entry row, its items and its tags, as they stood.
    entrySnapshot: text("entry_snapshot").notNull(),
    // JSON: each photo row, where its bytes were copied to, and when R2
    // says they were uploaded.
    photosSnapshot: text("photos_snapshot").notNull(),
    quarantinedAt: integer("quarantined_at").notNull(),
    retainUntil: integer("retain_until").notNull(),
  },
  (t) => [
    // The admin read, newest first; and a purge, when one exists, by date.
    index("quarantined_content_quarantined").on(t.quarantinedAt),
    index("quarantined_content_retain").on(t.retainUntil),
  ],
);
